# Generated by Django 4.0 on 2024-10-08 04:31

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('blog', '0002_termin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Maqola sarlavhasi')),
                ('anotatsiya', ckeditor.fields.RichTextField(verbose_name='Maqola matni')),
                ('key_words', models.CharField(max_length=200, verbose_name='Maqola kalit sozlari')),
                ('image', models.ImageField(upload_to='maqola_images/')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
