# Generated by Django 4.0 on 2024-10-08 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(max_length=200, verbose_name='Maqola muallifi'),
        ),
    ]
