# Generated by Django 4.0 on 2024-10-08 05:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='maqola_files/'),
            preserve_default=False,
        ),
    ]
