# Generated by Django 4.0 on 2024-10-08 10:42

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.AddField(
            model_name='article',
            name='full_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Maqola egasi FISH'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='kirish',
            field=ckeditor.fields.RichTextField(default=django.utils.timezone.now, verbose_name='Maqola kirish qismi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='work_study_place',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name="O'qish yoki ish joyi, ilmiy unvoni"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='anotatsiya',
            field=ckeditor.fields.RichTextField(verbose_name='Maqola anotatsiyasi'),
        ),
    ]
